import React from "react";import{createRoot}from"react-dom/client";import"./styles.css";
const industries=["Technology","Finance","Engineering","Marketing","Design","Education"];
const candidates=[["Aarav Sharma","Product Designer","7 yrs experience","12 projects"],["Meera Kapoor","Software Engineer","5 yrs experience","18 projects"],["Rohan Verma","Growth Manager","8 yrs experience","24 achievements"]];
function App(){return <main><header className="nav"><a className="brand" href="#top"><span className="mark">✓</span>PDP</a><button className="navbtn">Recruiters</button></header>
<section className="hero" id="top"><div className="eyebrow">PROFESSIONAL DIGITAL PROFILE</div><h1>Don’t just tell your career.<br/><span>Show it.</span></h1><p>A digital career showcase where experience, skills and achievements are supported by real proof of work.</p><div className="actions"><button className="primary">Create Your PDP — Free</button><button className="secondary">Explore Talent</button></div><div className="proofline">● VIDEO · PROJECTS · ACHIEVEMENTS · CERTIFICATES</div></section>
<section className="section"><div className="head"><div><div className="eyebrow">ON SHOWCASE</div><h2>People worth discovering.</h2></div><button className="textbtn">View all →</button></div><div className="cards">{candidates.map((c)=><article className="card" key={c[0]}><div className="video"><span>▶</span><small>CAREER INTRO</small></div><div className="body"><div className="verified">✓ PDP VERIFIED</div><h3>{c[0]}</h3><p>{c[1]}</p><div className="meta"><span>{c[2]}</span><span>{c[3]}</span></div><button className="outline">View PDP</button></div></article>)}</div></section>
<section className="section border"><div className="eyebrow">PROOF OF WORK</div><h2>What you did matters.<br/>Now show it.</h2><p className="intro">Turn a conventional resume into a visual record of your professional journey.</p><div className="proofgrid">{[["01","Career Video","Tell your story in your own voice."],["02","Experience","Show what you actually worked on."],["03","Projects","Put real work in front of recruiters."],["04","Achievements","Make milestones visible."],["05","Certificates","Keep credentials together."],["06","Testimonials","Let your work speak through others."]].map(x=><div className="proofitem" key={x[0]}><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
<section className="section"><div className="eyebrow">EXPLORE TALENT</div><h2>Find people by what they do.</h2><div className="industries">{industries.map(x=><button key={x}>{x}<span>↗</span></button>)}</div></section>
<section className="company"><div className="eyebrow">FOR COMPANIES</div><h2>Drop a job.<br/><span>Find the people.</span></h2><p>PDP will match job requirements with professionals who have demonstrated relevant skills and experience.</p><button className="primary">I’m Hiring</button></section>
<section className="cta"><div className="eyebrow">YOUR CAREER, DISPLAYED</div><h2>Your resume tells your story.<br/><span>Your PDP shows it.</span></h2><button className="primary">Create Your PDP — Free</button></section>
<footer><strong><span className="mark">✓</span> PDP</strong><span>Professional Digital Profile</span><nav><a href="#top">Talent</a><a href="#top">Opportunities</a><a href="#top">Companies</a><a href="#top">Verification</a></nav></footer></main>}createRoot(document.getElementById("root")).render(<App/>);